"""Public telemetry, metrics, and cost-calculation surface.

Owner: Elson & Daniel
"""

from backend.telemetry.cost_calculator import (
    CostRecordError,
    CostSummary,
    CostTotals,
    MissingModelPriceError,
    ModelCost,
    ModelRates,
    PricingError,
    PricingTable,
    TokenRates,
    UsageTotals,
    calculate_cost,
    calculate_costs,
)
from backend.telemetry.logger import (
    JsonlTelemetry,
    JsonlTelemetrySink,
    MalformedTelemetryRecordError,
    TelemetryRecord,
    TelemetrySerializationError,
    append_jsonl,
    append_record,
    iter_records,
    model_call_as_record,
    read_jsonl,
    read_records,
    routing_result_as_record,
)
from backend.telemetry.metrics import (
    DistributionMetrics,
    TelemetryMetricError,
    TelemetryMetrics,
    aggregate_metrics,
    calculate_metrics,
    compute_metrics,
    distribution,
    nearest_rank_percentile,
    summarize_records,
)

__all__ = [
    "CostRecordError",
    "CostSummary",
    "CostTotals",
    "DistributionMetrics",
    "JsonlTelemetry",
    "JsonlTelemetrySink",
    "MalformedTelemetryRecordError",
    "MissingModelPriceError",
    "ModelCost",
    "ModelRates",
    "PricingError",
    "PricingTable",
    "TelemetryMetricError",
    "TelemetryMetrics",
    "TelemetryRecord",
    "TelemetrySerializationError",
    "TokenRates",
    "UsageTotals",
    "aggregate_metrics",
    "append_jsonl",
    "append_record",
    "calculate_cost",
    "calculate_costs",
    "calculate_metrics",
    "compute_metrics",
    "distribution",
    "iter_records",
    "model_call_as_record",
    "nearest_rank_percentile",
    "read_jsonl",
    "read_records",
    "routing_result_as_record",
    "summarize_records",
]
